"""
DoodlerGAN & Animated Drawings IR — Intermediate Representation for AI Sketch & Animation.
All models are strictly defined using Pydantic v2.
"""

from typing import List, Literal, Optional
from pydantic import BaseModel, ConfigDict, Field

class FrozenModel(BaseModel):
    """Base for all Doodler IR models — strict, immutable-friendly."""
    model_config = ConfigDict(
        extra="forbid",
        validate_assignment=True,
        str_strip_whitespace=True,
    )

class PartNode(FrozenModel):
    """A specific part of a sketch to be generated by DoodlerGAN."""
    id: str
    part_type: Literal["body", "head", "eye", "mouth", "wing", "leg", "arm", "tail", "horn", "other"]
    order: int = Field(ge=0, description="The sequence order in which this part is drawn.")
    prompt: str = Field(description="Optional text prompt or constraint for this specific part.")

class SketchSequence(FrozenModel):
    """The sequence of parts to draw a complete character/creature."""
    id: str = "sketch-main"
    parts: List[PartNode] = Field(default_factory=list)
    creature_name: str = ""
    lore: str = Field(default="", description="The generated backstory or lore for this creature.")

class SketchBrief(FrozenModel):
    """The initial user input for the creative sketch."""
    user_prompt: str
    style: str = "creative"
    num_parts_budget: int = Field(default=5, ge=1, le=20)

class AnimationScene(FrozenModel):
    """Defines a single chronological sequence in the animation."""
    start_time: float = Field(ge=0, description="Start time in seconds")
    end_time: float = Field(gt=0, description="End time in seconds")
    motion_type: Literal["walk", "run", "jump", "dance", "wave", "idle"] = "idle"
    sfx_prompt: str = Field(default="", description="Description of the sound effect (Foley) for this scene.")

class TimelineSequence(FrozenModel):
    """The chronological ordered list of scenes."""
    id: str = "timeline-main"
    scenes: List[AnimationScene] = Field(default_factory=list)

class DoodlerStudioSpec(FrozenModel):
    """The complete specification containing both sketch and timeline plans."""
    brief: SketchBrief
    sketch: SketchSequence
    timeline: TimelineSequence
    style_id: str = Field(default="symmetrical_pastel_cinema", description="Art style ID from starter_pack.json")
