[theme]
base = "light"
primaryColor = "#9a7b4f"
backgroundColor = "#f3efe6"
secondaryBackgroundColor = "#ebe6db"
textColor = "#14221f"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
